{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nanodeploy-operator
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    app: nanodeploy-operator
spec:
  selector:
    matchLabels:
      app: nanodeploy-operator
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}