apiVersion: v1
kind: Service
metadata:
  name: nanodeploy-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: nanodeploy-operator
spec:
  selector:
    app: nanodeploy-operator
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
    - name: api
      port: {{ .Values.api.port }}
      targetPort: api
    - name: health
      port: {{ .Values.healthProbe.port }}
      targetPort: health